In [3]:
import numpy as np
import tensorflow as tf
# tf.disable_v2_behavior()

sess = tf.InteractiveSession()

embedding = tf.Variable(np.identity(5, dtype=np.int32))
input_ids = tf.placeholder(dtype=tf.int32, shape=[None])
input_embedding = tf.nn.embedding_lookup(embedding, input_ids)

/home/ztl/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/client/session.py:1735: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [4]:
sess.run(tf.global_variables_initializer())

In [5]:
print(embedding.eval())
print(sess.run(input_embedding, feed_dict={input_ids:[1, 2, 3, 0, 3, 2, 1]}))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]]


In [6]:
# import tensorflow as tf
tf.__version__

'1.14.0'

In [20]:
input_ids = tf.placeholder(dtype=tf.int32, shape=[3,2])
input_embedding = tf.nn.safe_embedding_lookup(embedding, input_ids)
out = sess.run(input_embedding, feed_dict={input_ids:[[1, 2], [2, 1], [3, 0]]})
print(out.shape, out)

AttributeError: module 'tensorflow._api.v1.nn' has no attribute 'safe_embedding_lookup'

In [9]:
norm = tf.contrib.distributions.Normal(loc=0., scale=1.)

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.


In [10]:
import pickle as pkl
year = 2005
index = pkl.load(open('../aminer/individual_data/index_' + str(year) + '.pkl', 'rb'))

AttributeError: 'list' object has no attribute 'keys'

In [12]:
rank = pkl.load(open('../aminer/select_index_train.pkl','rb'))
rank.shape

(3000,)

In [15]:
index_table_P1P = index[0][:,rank,:]
index_table_P1P.shape, np.min(index_table_P1P), np.max(index_table_P1P)

((5, 3000, 100), -1, 509676)

In [16]:
index_p1p_flat = index_table_P1P.flatten()
index_p1p_flat.shape

(1500000,)

In [17]:
import pandas as pd
df = pd.DataFrame({'a':index_p1p_flat})
df.describe()

a
count  1.500000e+06
mean   1.392024e+04
std    6.059389e+04
min   -1.000000e+00
25%   -1.000000e+00
50%   -1.000000e+00
75%   -1.000000e+00
max    5.096760e+05

In [18]:
index = pkl.load(open('../aps/index_' + str(year) + '.pkl', 'rb'))
index.shape

AttributeError: 'list' object has no attribute 'shape'

In [19]:
index[0].shape

(5, 17953, 100)

In [22]:
alignment_ids = pkl.load(open('../aminer/individual_data/alignment_nodes.pkl','rb'))
len(alignment_ids), list(alignment_ids.keys())

(10,
 ['aligment_id_2000',
  'aligment_id_2001',
  'aligment_id_2002',
  'aligment_id_2003',
  'aligment_id_2004',
  'aligment_id_2005',
  'aligment_id_2006',
  'aligment_id_2007',
  'aligment_id_2008',
  'aligment_id_2009'])

In [24]:
aid_2000 = alignment_ids['aligment_id_'+str(year-5)]
len(aid_2000)


2

In [26]:
len(aid_2000[0]), len(aid_2000[1])

(148869, 148869)

In [28]:
df=pd.DataFrame({'AID0':aid_2000[0], 'AID1':aid_2000[1]})
df.describe()


AID0           AID1
count  148869.000000  148869.000000
mean   139959.141601  152663.594026
std     84552.005698   93570.926038
min         1.000000       1.000000
25%     64527.000000   68115.000000
50%    137935.000000  151273.000000
75%    213486.000000  233967.000000
max    289064.000000  317339.000000

In [35]:
a = tf.zeros((3,2))
a

<tf.Tensor 'zeros_2:0' shape=(3, 2) dtype=float32>

In [45]:
b = np.array(a)
b

array(<tf.Tensor 'zeros_2:0' shape=(3, 2) dtype=float32>, dtype=object)

In [40]:
graph_1 = pkl.load(open('../aps/individual_graph_' + str(year - 5) + '_nf.pkl', 'rb'))
adj = graph_1['adj'][0]
adj.shape

(126152, 126152)

In [46]:
index_table_P1P = tf.placeholder(name='index_P1P', shape=(3, 2), dtype=tf.int32)
index_table_P1P

<tf.Tensor 'index_P1P:0' shape=(3, 2) dtype=int32>

In [54]:
index_table_P1P2 = index_table_P1P + 1
index_table_P1P2

<tf.Tensor 'add_12:0' shape=(3, 2) dtype=int32>

In [55]:
index_table_P1P3 = index_table_P1P + tf.ones_like(index_table_P1P)
index_table_P1P3

<tf.Tensor 'add_13:0' shape=(3, 2) dtype=int32>

In [53]:
index_table_P1P2 = index_table_P1P + tf.ones_like(index_table_P1P)
index_table_P1P2

<tf.Tensor 'add_11:0' shape=(3, 2) dtype=int32>