In [2]:
import pickle as pkl
year = 2005
f = open('../aminer/individual_data/graph_' + str(year - 5) + '_nf.pkl', 'rb')
graph_1 = pkl.load(f)
graph_1

{'adj': [<289067x289067 sparse matrix of type '<class 'numpy.float64'>'
  	with 394738 stored elements in Compressed Sparse Row format>,
  <289067x289067 sparse matrix of type '<class 'numpy.float64'>'
  	with 122866 stored elements in Compressed Sparse Row format>,
  <289067x289067 sparse matrix of type '<class 'numpy.float64'>'
  	with 47528 stored elements in Compressed Sparse Row format>,
  <289067x289067 sparse matrix of type '<class 'numpy.float64'>'
  	with 475969 stored elements in Compressed Sparse Row format>,
  <289067x289067 sparse matrix of type '<class 'numpy.float64'>'
  	with 289067 stored elements in Compressed Sparse Row format>],
 'feature': array([[ 1.09316985,  1.71707666,  1.52321106,  1.74542294],
        [-0.72327112, -0.60343884, -0.23896099, -0.51400074],
        [ 0.86622103,  0.61580427,  0.58076019,  0.83515416],
        ...,
        [-0.8723664 , -0.79892077, -0.40560427, -0.98031332],
        [ 1.02743948,  1.78152733,  1.38482124,  1.10499206],
        [

In [3]:
import numpy as np
mx = graph_1['adj'][0]
mx.sum(1)

matrix([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]])

In [6]:
import scipy.sparse as sp
row = np.array([0, 0, 1, 3, 1, 0, 0])
col  = np.array([0, 2, 1, 3, 1, 0, 0])
data = np.array([1, 1, 1, 1, 1, 1, 1])
indices = np.mat([row, col]).transpose()
indices

matrix([[0, 0],
        [0, 2],
        [1, 1],
        [3, 3],
        [1, 1],
        [0, 0],
        [0, 0]])

In [18]:
import tensorflow as tf
norm = tf.distributions.Normal(loc=0., scale=1.)
# norm = tf.keras.initializers.glorot_normal(loc=0., scale=1.)#glorot_normal

AttributeError: module 'tensorflow' has no attribute 'distributions'

In [22]:
import sys
sys.path.append('/nfs3-p1/zhangtl/utils')
from util import myout
rank = pkl.load(open('../aminer/select_index_train.pkl','rb'))
myout(rank)

rank : shape=(3000,), [   2    7    9 ... 9009 9045 9062]


In [23]:
log_labels = pkl.load(open('../aminer/cumulative_log_labels_new.pkl','rb'))
myout(log_labels)

log_labels : len=13, {'P2005_label':                  P  citation_2006  ...  citation_2017  citation_2018
0       2115764225       0.000000  ...       1.098612       1.098612
1       1895301123       0.000000  ...       1.098612       1.098612
2       2046820355       0.000000  ...       0.000000       0.000000
3       1911291911       1.098612  ...       2.397895       2.397895
4       2104754184       0.693147  ...       0.693147       0.693147
...            ...            ...  ...            ...            ...
105595  1587806195       0.693147  ...       1.098612       1.098612
105596  2117074932       1.098612  ...       1.609438       1.609438
105597  2016149493       0.000000  ...       1.609438       1.609438
105598  2145386488       1.386294  ...       3.218876       3.218876
105599  2128084987       1.386294  ...       3.218876       3.295837

[105600 rows x 14 columns], 'P2006_label':                  P  citation_2007  ...  citation_2017  citation_2018
0       2096365568    

In [24]:
labels_year = log_labels['P' + str(year) + '_label']
labels = labels_year.iloc[rank, 1:6].values
myout(labels_year, labels)

labels_year =                  P  citation_2006  ...  citation_2017  citation_2018
0       2115764225       0.000000  ...       1.098612       1.098612
1       1895301123       0.000000  ...       1.098612       1.098612
2       2046820355       0.000000  ...       0.000000       0.000000
3       1911291911       1.098612  ...       2.397895       2.397895
4       2104754184       0.693147  ...       0.693147       0.693147
...            ...            ...  ...            ...            ...
105595  1587806195       0.693147  ...       1.098612       1.098612
105596  2117074932       1.098612  ...       1.609438       1.609438
105597  2016149493       0.000000  ...       1.609438       1.609438
105598  2145386488       1.386294  ...       3.218876       3.218876
105599  2128084987       1.386294  ...       3.218876       3.295837

[105600 rows x 14 columns]
labels : shape=(3000, 5)
[[0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0

In [25]:
list(log_labels.keys())

['P2005_label',
 'P2006_label',
 'P2007_label',
 'P2008_label',
 'P2009_label',
 'P2010_label',
 'P2011_label',
 'P2012_label',
 'P2013_label',
 'P2014_label',
 'P2015_label',
 'P2016_label',
 'P2017_label']

In [29]:
log_labels['P' + str(2015) + '_label'].describe()

P  citation_2016  citation_2017  citation_2018
count  2.077630e+05  207763.000000  207763.000000  207763.000000
mean   1.955154e+09       0.517302       0.840694       0.967233
std    4.200042e+08       0.684933       0.883498       0.954562
min    7.209000e+04       0.000000       0.000000       0.000000
25%    1.879785e+09       0.000000       0.000000       0.000000
50%    2.057533e+09       0.000000       0.693147       0.693147
75%    2.217058e+09       0.693147       1.386294       1.609438
max    2.898530e+09       7.351800       8.423542       8.910721

In [30]:
index = pkl.load(open('../aminer/individual_data/index_' + str(year) + '.pkl', 'rb'))
index

[array([[[246700, 249668, 272071, ...,     -1,     -1,     -1],
         [    -1,     -1,     -1, ...,     -1,     -1,     -1],
         [ 69695,  96908, 120480, ...,     -1,     -1,     -1],
         ...,
         [    -1,     -1,     -1, ...,     -1,     -1,     -1],
         [216625, 121316,     -1, ...,     -1,     -1,     -1],
         [ 18278,  30466, 188738, ...,     -1,     -1,     -1]],
 
        [[147594, 149156, 307964, ...,     -1,     -1,     -1],
         [ 41280,     -1,     -1, ...,     -1,     -1,     -1],
         [ 49509, 211767,  78342, ...,     -1,     -1,     -1],
         ...,
         [    -1,     -1,     -1, ...,     -1,     -1,     -1],
         [225212, 228767,  89125, ...,     -1,     -1,     -1],
         [177770, 182491, 115550, ...,     -1,     -1,     -1]],
 
        [[140609, 166442, 168282, ...,     -1,     -1,     -1],
         [240172,  45422,     -1, ...,     -1,     -1,     -1],
         [ 54329, 240001, 261468, ...,     -1,     -1,     -1],
      

In [34]:
for i in range(len(index)):
    print(index[i].shape)

(5, 105600, 100)
(5, 105600, 20)
(5, 105600, 1)
(5, 105600, 15)


In [35]:
index_table_P1P = index[0][:,rank,:]
myout(index_table_P1P)

index_table_P1P : shape=(5, 3000, 100)
[[[ 69695  96908 120480 ...     -1     -1     -1]
  [110839  32579  50958 ...     -1     -1     -1]
  [224586     -1     -1 ...     -1     -1     -1]
  ...
  [226797     -1     -1 ...     -1     -1     -1]
  [ 30406     -1     -1 ...     -1     -1     -1]
  [131371  69743  55790 ...     -1     -1     -1]]

 [[ 49509 211767  78342 ...     -1     -1     -1]
  [219614 183348  36312 ...     -1     -1     -1]
  [ 82091 135322  89961 ...     -1     -1     -1]
  ...
  [283150     -1     -1 ...     -1     -1     -1]
  [    -1     -1     -1 ...     -1     -1     -1]
  [  9170 230843 178270 ...     -1     -1     -1]]

 [[ 54329 240001 261468 ...     -1     -1     -1]
  [248849 207561  39910 ...     -1     -1     -1]
  [152576  10643 100696 ...     -1     -1     -1]
  ...
  [321452     -1     -1 ...     -1     -1     -1]
  [ 23583     -1     -1 ...     -1     -1     -1]
  [352355 151425  10079 ...     -1     -1     -1]]

 [[ 62227 283088 308635 ...     -1   

In [ ]:
alignment_ids = pkl.load(open('../aminer/individual_data/alignment_nodes.pkl','rb'))
len(aligment_ids), list(alignment_ids.keys())