In [1]:
import pandas as pd
NOTE_PATH = '/nfs3-p1/zty/2021-FanXing/Academic-Networks/Academic_GNN_Module/'
DBLP_PATH = NOTE_PATH + 'dblpv13/'
df = pd.read_csv(f'{DBLP_PATH}/ids_map.csv')

In [2]:
df_author = df[df['Type']=='Author']
print(df_author.head())

     Type                       _ID  Index
0  Author  53f3186ddabfae9a84425c58      0
1  Author  53f3186fdabfae9a84425cde      1
2  Author  53f3186fdabfae9a84425cfb      2
3  Author  53f31870dabfae9a84425d19      3
4  Author  53f31870dabfae9a84425d53      4


In [3]:
df_author.columns

Index(['Type', '_ID', 'Index'], dtype='object')

In [4]:
df_authors = pd.read_csv(f'{DBLP_PATH}/dblp.authors.csv')
print(df_authors.head())

                        aid                 name  year  \
0  53f64e03dabfae0633f1626b        Stephen Beale   0.0   
1  53f46ff1dabfaedd74e8f51b  Amirhossein Shirazi   0.0   
2  5405f291dabfae450f3e4cd9       Marcel Ausloos   0.0   
3  53f44b03dabfaeee22a09d3a           Rachel Lee   0.0   
4  53f46b90dabfaeecd6a21167       Nazli Goharian   0.0   

                                                 org  
0    Information Sciences Institute|University of S.  
1  Department of Physics, Shahid Beheshti Univers...  
2  GRAPES, rue de la Belle Jardiniere 483, B-4031...  
3                                                NaN  
4                                                NaN  


In [6]:
aids = ['56314f0045cedb3399d765d2', '53f48c0fdabfaea7cd1cdf72', '53f454f4dabfaec09f201277', \
    '53f42ff1dabfaee4dc7395aa', '53f4ba75dabfaed83977b7db', '53f366a7dabfae4b3499c6fe', '53f48919dabfaee4dc8b219c']
a_indexs = []
for idx in aids:
    df3 = df_author[df_author['_ID']==idx]
    ss = df3['Index'].iloc[0]
    a_indexs.append((ss, idx))
    print(f'{ss}: {idx}')

3178630: 56314f0045cedb3399d765d2
1548191: 53f48c0fdabfaea7cd1cdf72
1152321: 53f454f4dabfaec09f201277
390906: 53f42ff1dabfaee4dc7395aa
1572517: 53f4ba75dabfaed83977b7db
57714: 53f366a7dabfae4b3499c6fe
1546523: 53f48919dabfaee4dc8b219c


In [7]:
a_indexs

[(3178630, '56314f0045cedb3399d765d2'),
 (1548191, '53f48c0fdabfaea7cd1cdf72'),
 (1152321, '53f454f4dabfaec09f201277'),
 (390906, '53f42ff1dabfaee4dc7395aa'),
 (1572517, '53f4ba75dabfaed83977b7db'),
 (57714, '53f366a7dabfae4b3499c6fe'),
 (1546523, '53f48919dabfaee4dc8b219c')]

In [8]:
import dgl
import torch

graph_list, _ = dgl.load_graphs('../save3/graph_h_index.graph')
graph = graph_list[0]
print(graph)

Using backend: pytorch


Graph(num_nodes={'author': 36288, 'country': 54, 'field': 142726, 'org': 379, 'paper': 5319925, 'topic': 16081, 'venue': 46347},
      num_edges={('country', 'has', 'org'): 432, ('field', 'has', 'venue'): 29480166, ('org', 'has', 'author'): 721202, ('paper', 'cites', 'paper'): 25626821, ('paper', 'written', 'author'): 3728457, ('topic', 'contains', 'paper'): 13160952, ('venue', 'publishes', 'paper'): 3278873},
      metagraph=[('country', 'org', 'has'), ('org', 'author', 'has'), ('field', 'venue', 'has'), ('venue', 'paper', 'publishes'), ('paper', 'paper', 'cites'), ('paper', 'author', 'written'), ('topic', 'paper', 'contains')])


In [12]:
import sys
sys.path.append('../')
from util import myout
author_ID = graph.nodes['author'].data['_ID']
author_h_index = graph.nodes['author'].data['h_index']
myout(author_ID, author_h_index)

author_ID : shape=torch.Size([36288]), tensor([    254,     255,     874,  ..., 3302961, 3304332, 3306903])
author_h_index : shape=torch.Size([36288]), tensor([7., 3., 9.,  ..., 1., 0., 0.])


In [17]:
tar_index = torch.tensor([item[0] for item in a_indexs])
myout(tar_index)

tar_index : shape=torch.Size([7]), tensor([3178630, 1548191, 1152321,  390906, 1572517,   57714, 1546523])


In [19]:

for i in range(len(tar_index)):
    idx = torch.where(author_ID==tar_index[i])[0]
    myout(idx)
    print(author_h_index[idx])

idx : shape=torch.Size([0]), tensor([], dtype=torch.int64)
tensor([])
idx : shape=torch.Size([1]), tensor([16032])
tensor([24.])
idx : shape=torch.Size([0]), tensor([], dtype=torch.int64)
tensor([])
idx : shape=torch.Size([1]), tensor([3847])
tensor([18.])
idx : shape=torch.Size([1]), tensor([17134])
tensor([21.])
idx : shape=torch.Size([1]), tensor([480])
tensor([19.])
idx : shape=torch.Size([1]), tensor([15912])
tensor([13.])


In [ ]:
h_author = graph.nodes['author'].data['h_index']

In [20]:
a = [('2020', 'Aho, Alfred V.', '56314f0045cedb3399d765d2', '3178630', -1, 67),
('2020', 'Jeffrey D. Ullman', '53f48c0fdabfaea7cd1cdf72', '1548191', 24, 117),
('2019', 'Edwin E. Catmull', '53f454f4dabfaec09f201277', '1152321', -1, 6),
('2019', 'Pat Hanrahan', '53f42ff1dabfaee4dc7395aa', '390906', 18, 93),
('2018', 'Yoshua Bengio', '53f4ba75dabfaed83977b7db', '1572517', 21, 196),
('2018', 'Geoffrey E. Hinton', '53f366a7dabfae4b3499c6fe', '57714', 19, 166),
('2018', 'Y. LeCun', '53f48919dabfaee4dc8b219c', '1546523', 13, 129)]
print(a)

[('2020', 'Aho, Alfred V.', '56314f0045cedb3399d765d2', '3178630', -1, 67), ('2020', 'Jeffrey D. Ullman', '53f48c0fdabfaea7cd1cdf72', '1548191', 24, 117), ('2019', 'Edwin E. Catmull', '53f454f4dabfaec09f201277', '1152321', -1, 6), ('2019', 'Pat Hanrahan', '53f42ff1dabfaee4dc7395aa', '390906', 18, 93), ('2018', 'Yoshua Bengio', '53f4ba75dabfaed83977b7db', '1572517', 21, 196), ('2018', 'Geoffrey E. Hinton', '53f366a7dabfae4b3499c6fe', '57714', 19, 166), ('2018', 'Y. LeCun', '53f48919dabfaee4dc8b219c', '1546523', 13, 129)]


In [49]:
df_t = pd.DataFrame(columns=['Index', '_ID', 'year', 'name',  'num_paper', 'h-index','Aminer h-index', 'Google h-index'])
df_t['year'] = [i[0] for i in a]
df_t['name'] = [i[1] for i in a]
df_t['_ID'] = [i[2] for i in a]
df_t['Index'] = [i[3] for i in a]
df_t['h-index'] = [i[4] for i in a]
df_t['Google h-index'] = [i[5] for i in a]
df_t['num_paper'] = [1, 292, 9, 195, 599, 247, 215]
df_t['Aminer h-index'] = [-1, -1, 12, 97, 194, 184, 134]
df_t

Index                       _ID  year                name  num_paper  \
0  3178630  56314f0045cedb3399d765d2  2020      Aho, Alfred V.          1   
1  1548191  53f48c0fdabfaea7cd1cdf72  2020   Jeffrey D. Ullman        292   
2  1152321  53f454f4dabfaec09f201277  2019    Edwin E. Catmull          9   
3   390906  53f42ff1dabfaee4dc7395aa  2019        Pat Hanrahan        195   
4  1572517  53f4ba75dabfaed83977b7db  2018       Yoshua Bengio        599   
5    57714  53f366a7dabfae4b3499c6fe  2018  Geoffrey E. Hinton        247   
6  1546523  53f48919dabfaee4dc8b219c  2018            Y. LeCun        215   

   h-index  Aminer h-index  Google h-index  
0       -1              -1              67  
1       24              -1             117  
2       -1              12               6  
3       18              97              93  
4       21             194             196  
5       19             184             166  
6       13             134             129

In [23]:
import json
out = json.load(open('out.json', 'r'))
len(out)

7

In [26]:
turing_name = [i[1] for i in a]
for i,item in enumerate(out):
    print(turing_name[i], len(item))

Aho, Alfred V. 1
Jeffrey D. Ullman 292
Edwin E. Catmull 9
Pat Hanrahan 195
Yoshua Bengio 599
Geoffrey E. Hinton 247
Y. LeCun 215


In [27]:
out[0]

[['56314f0045cedb3399d765d2',
  '5c86c82c4895d9cbc698ff2b',
  'Indexed grammars -- An extension of context free grammars',
  [{'_id': '56314f0045cedb3399d765d2', 'name': 'Aho, Alfred V.'}],
  1967]]

In [39]:
df_out = pd.DataFrame(columns=['name', 'year', 'title'])
ll = []
idx = 5
for idx in range(len(turing_name)):
    # print(turing_name[idx])
    for item in out[idx]:
        ll.append((turing_name[idx], item[-1], item[2]))

In [40]:
df_out['name'] = [item[0] for item in ll]
df_out['year'] = [item[1] for item in ll]
df_out['title'] = [item[2] for item in ll]

In [41]:
df_out.head()

name  year                                              title
0     Aho, Alfred V.  1967  Indexed grammars -- An extension of context fr...
1  Jeffrey D. Ullman  1980                                Universal Instances
2  Jeffrey D. Ullman  1975     Evaluating Polynomials at Fixed Sets of Points
3  Jeffrey D. Ullman  1969                             Halting Stack Automata
4  Jeffrey D. Ullman  1972                            Flow graph reducibility

In [42]:
df_out.to_csv('../save3/turing.csv')